### ISSUE TITLE
Is the .ignore file necessary?

### ISSUE THREAD

**Issue by GeorgPessler** [cginternals/cmake-init#106]
I can not find where this file is used, so I wondered whether this file is necessary at all?

**Comment by scheibel** [comment]
Indeed, this file is not used within cmake-init. This file is a blacklist of file paths to ignore for the line counting service from the [tokei](https://github.com/XAMPPRocky/tokei) line counter. Explicit documentation on this is pending.

**Comment by GeorgPessler** [comment]
Thank you for the information. The tool looks interresting.
