### ISSUE TITLE
Update GetGitRevisionDescription.cmake and GetGitRevisionDescription.cmake.in

### ISSUE THREAD

**Issue by FalseCAM** [cginternals/cmake-init#33]
Hi I have one cmake-init project as submodule in another project.
I have got following error:

> CMake Error at build/confdesc/CMakeFiles/git-data/grabRef.cmake:36 (file):
>   file failed to open for reading (No such file or directory):
> 
> ```
> /home/.../workspace/hyphaframework/build/confdesc/CMakeFiles/git-data/head-ref
> ```
> 
> Call Stack (most recent call first):
>   confdesc/cmake/GetGitRevisionDescription.cmake:79 (include)
>   confdesc/CMakeLists.txt:35 (get_git_head_revision)

I could fix it by replacing  GetGitRevisionDescription.cmake and GetGitRevisionDescription.cmake.in from [https://github.com/rpavlik/cmake-modules](url)

**Comment by scheibel** [comment]
We merged your PR #34 so I think this issue can be closed. Thanks for contributing!
