### ISSUE TITLE
Remove unnecessary files from googletest and googlemock

### ISSUE THREAD

**Issue by scheibel** [cginternals/cmake-init#42]
Currently, the googletest and googlemock test suites bloat up a cmake-init project setup.
We should remove all unnecessary files (e.g., documentation).

**Comment by sbusch42** [comment]
Is this done?

**Comment by scheibel** [comment]
No.

**Comment by scheibel** [comment]
For current progress see #97 and https://github.com/cginternals/cppfs/issues/24.

**Comment by scheibel** [comment]
We just removed googletest and googlemock from the template to use them externally.
Thus, this issue is rendered obsolete.
