### ISSUE TITLE
Add individual check-targets to IDE folder

### ISSUE THREAD

**Issue by sbusch42** [cginternals/cmake-init#63]
The global check-targets are in folder "Maintenance", but the targets for the individual projects are still not.

**Comment by scheibel** [comment]
Sorry; seems like I missed that.

**Comment by scheibel** [comment]
Fixed since ffb1664f554764c8db0dee05292d4fbc39791808.

**Comment by scheibel** [comment]
Seems fixed since 724e4a18edc1efe30ea20c1567c34786a988976c.
