### ISSUE TITLE
Update/fix googletest for VS2017 v15.5

### ISSUE THREAD

**Issue by j-o** [cginternals/cmake-init#77]
googletest doesn't compile with the recent VS2017 update to v15.5, see https://github.com/google/googletest/issues/1318.

**Comment by j-o** [comment]
googletest is fixed now, so an update would be in order. Did you change anything or just dump the entire source into cmake-init?

**Comment by scheibel** [comment]
That was our way to go. I hope everything works as expected with just replacing the contents in `cmake-init/source/tests/googletest`.

**Comment by scheibel** [comment]
Is this fixed with #78?

**Comment by j-o** [comment]
Yes
